services:
  vauxl:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      network: host
    ports:
      - "8008:8008"
    environment:
      VAUXL_DATABASE__URL: postgres://vauxl:vauxl@db/vauxl?sslmode=disable
      VAUXL_REDIS__URL: redis://cache:6379
      RUST_LOG: vauxl_server=debug
    volumes:
      - vauxl_data:/app/data
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

  db:
    image: postgres:16
    network_mode: "host"
    environment:
      POSTGRES_USER: vauxl
      POSTGRES_PASSWORD: vauxl
      POSTGRES_DB: vauxl
      POSTGRES_HOST_AUTH_METHOD: trust
#    ports: ["127.0.0.1:${VAUXL_POSTGRES_PORT:-5432}:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vauxl"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7-alpine
    ports: ["6379:6379"]

volumes:
  pgdata: {}
  vauxl_data: {}
