FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates libssl3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY target/release/vauxl-server ./vauxl-server
COPY config/ ./config/
COPY docker/complement-entrypoint.sh ./complement-entrypoint.sh

EXPOSE 8008
EXPOSE 8448
ENTRYPOINT ["/bin/sh", "/app/complement-entrypoint.sh"]
